Added new and create for activities
Ichenn92/elixir pull request #13
Opened 2021-03-18 21:22 UTC by michaellaurac

2021-03-18 21:45 UTC, Ichenn92 requested changes

2021-03-18 21:45 UTC, Ichenn92 commented on app/assets/stylesheets/components/_activity.scss
> +}
Toutes ces classes n'existent-elles pas déjà ailleurs? il me semble que @clem13-coder les a déjà écrites

2021-03-18 21:45 UTC, Ichenn92 commented on app/controllers/activities_controller.rb
> +      #@activity.photo.attach(@photo)
Clem a installé cloudinary. il faut accepter sa PR et merge son code.
tu pourras ensuite appelé ta fonction attach photo ;)

2021-03-19 07:33 UTC, michaellaurac commented on app/assets/stylesheets/components/_activity.scss
> +}
Yes dans le component session_user. j'ai effacé le component activity.
Il faudrait peut-être renommer session_user en _formular.scss

2021-03-19 07:34 UTC, michaellaurac commented on app/controllers/activities_controller.rb
> +      #@activity.photo.attach(@photo)
PR acceptée

2021-03-19 08:25 UTC, Ichenn92 commented on app/assets/stylesheets/components/_activity.scss
> +}
si il ne contient que ça oui effectivement.
si il contient d'autre chose, peut-être sortir ces classes dans un composant _formular.scss

2021-03-20 09:12 UTC, clem13-coder approved these changes

2021-03-20 09:44 UTC, michaellaurac commented on app/assets/stylesheets/components/_activity.scss
> +}
Done using _form.scss

2021-03-20 09:46 UTC, Ichenn92 approved these changes

2021-03-20 09:46 UTC, merged